let name = 'Pedro';
console.log(name);
console.log(name.charAt(2));
console.log(name.charCodeAt(0));
console.log(name.concat(' Silva'));
console.log(name);
name = name.concat(' Silva');
console.log(name);
console.log(name.indexOf('e'));
console.log(name.indexOf('a'));
console.log(name.match('Silva'));
console.log(name.replace('Silva', 'Medeiros'));
console.log(name);
let names = 'Pedro;Ana;Maria;Carolina';
console.log(names);
console.log(names.split(';'));
console.log(name.substring(0, 5));
console.log(name.substring(5));
name = ' Pedro Silva ';
console.log(name);
console.log(name.trim());